---
- name: Configure interfaces
  cisco.ios.ios_config:
    lines:
      - interface FastEthernet0/1
      - switchport mode access
      - switchport access vlan 10
      - no shutdown
      - exit
