---
- name: Enable ssh_config
  cisco.ios.ios_config:
    lines:
      - ip domain-name sagir.local
      - username admin privilege 15 secret admin123
      - crypto key generate rsa modulus 2048
      - line vty 0 4
      - transport input ssh
      - login local
      - exit
    save: true
