---
- name: Full Cisco Switch Automation
  hosts: cisco_switches
  gather_facts: false
  become_method: enable 
  roles:
    - base_config
    - vlan_config
    - interface_config
    - ssh_config
